import type { SceneGraph } from '@pascal-app/core/clone-scene-graph'
import type { AnyNode, AnyNodeId } from '@pascal-app/core/schema'

/**
 * 40′ Class A motorhome envelope. Deterministic ids (`site_rv`, `level_main`,
 * …) are regenerated by `cloneSceneGraph` before the template is applied.
 *
 * Coordinate frame: XZ plane, origin at coach center. Width (X) is the exterior
 * body width; length (Z) runs front (−Z) to rear (+Z). Three levels stack in the
 * building: chassis (pass-through bays, level −1), main (living floor, level 0),
 * roof (reference plane for A/C, solar, vents, level 1).
 */

const HALF_W = 2.5908 / 2 // exterior body half-width (102")
const HALF_L = 12.192 / 2 // coach half-length (40')
const WALL_HEIGHT = 2.0 // interior wall height
const WALL_THICKNESS = 0.05

// Bay boundaries along Z, front (−) to rear (+): 7 pass-through compartments.
const BAY_BANDS: Array<{ role: string; name: string; z0: number; z1: number }> = [
  { role: 'generator', name: 'Generator bay', z0: -HALF_L, z1: -4.5 },
  { role: 'battery', name: 'Battery bay', z0: -4.5, z1: -3.3 },
  { role: 'propane', name: 'Propane bay', z0: -3.3, z1: -2.1 },
  { role: 'fresh-tank', name: 'Fresh water tank', z0: -2.1, z1: -0.5 },
  { role: 'grey-tank', name: 'Grey tank', z0: -0.5, z1: 1.0 },
  { role: 'black-tank', name: 'Black tank', z0: 1.0, z1: 2.5 },
  { role: 'engine', name: 'Engine bay', z0: 2.5, z1: HALF_L },
]

function buildNodes(): AnyNode[] {
  const site = {
    object: 'node',
    id: 'site_rv' as AnyNodeId,
    type: 'site',
    parentId: null,
    visible: true,
    metadata: {},
    polygon: {
      type: 'polygon',
      points: [
        [-8, -8],
        [8, -8],
        [8, 8],
        [-8, 8],
      ],
    },
    children: ['building_rv' as AnyNodeId],
  } as unknown as AnyNode

  const building = {
    object: 'node',
    id: 'building_rv' as AnyNodeId,
    type: 'building',
    parentId: 'site_rv' as AnyNodeId,
    visible: true,
    metadata: {},
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    children: ['level_chassis', 'level_main', 'level_roof'] as AnyNodeId[],
  } as unknown as AnyNode

  const wallDefs = [
    { id: 'wall_n', start: [-HALF_W, -HALF_L], end: [HALF_W, -HALF_L] },
    { id: 'wall_e', start: [HALF_W, -HALF_L], end: [HALF_W, HALF_L] },
    { id: 'wall_s', start: [HALF_W, HALF_L], end: [-HALF_W, HALF_L] },
    { id: 'wall_w', start: [-HALF_W, HALF_L], end: [-HALF_W, -HALF_L] },
  ]
  const walls = wallDefs.map(
    (w) =>
      ({
        object: 'node',
        id: w.id as AnyNodeId,
        type: 'wall',
        parentId: 'level_main' as AnyNodeId,
        visible: true,
        metadata: { locked: true },
        children: [],
        thickness: WALL_THICKNESS,
        height: WALL_HEIGHT,
        start: w.start,
        end: w.end,
        frontSide: 'unknown',
        backSide: 'unknown',
      }) as unknown as AnyNode,
  )

  const bays = BAY_BANDS.map(
    (b) =>
      ({
        object: 'node',
        id: `zone_bay_${b.role}` as AnyNodeId,
        type: 'zone',
        parentId: 'level_chassis' as AnyNodeId,
        visible: true,
        metadata: { bayRole: b.role, locked: true },
        name: b.name,
        color: '#94a3b8',
        polygon: [
          [-HALF_W, b.z0],
          [HALF_W, b.z0],
          [HALF_W, b.z1],
          [-HALF_W, b.z1],
        ],
      }) as unknown as AnyNode,
  )

  const levelChassis = {
    object: 'node',
    id: 'level_chassis' as AnyNodeId,
    type: 'level',
    parentId: 'building_rv' as AnyNodeId,
    visible: true,
    metadata: {},
    level: -1,
    children: bays.map((b) => b.id) as AnyNodeId[],
  } as unknown as AnyNode

  const levelMain = {
    object: 'node',
    id: 'level_main' as AnyNodeId,
    type: 'level',
    parentId: 'building_rv' as AnyNodeId,
    visible: true,
    metadata: {},
    level: 0,
    children: walls.map((w) => w.id) as AnyNodeId[],
  } as unknown as AnyNode

  const levelRoof = {
    object: 'node',
    id: 'level_roof' as AnyNodeId,
    type: 'level',
    parentId: 'building_rv' as AnyNodeId,
    visible: true,
    metadata: {},
    level: 1,
    children: [],
  } as unknown as AnyNode

  return [site, building, levelChassis, levelMain, levelRoof, ...walls, ...bays]
}

function buildTemplate(): SceneGraph {
  const nodes: Record<AnyNodeId, AnyNode> = {}
  for (const node of buildNodes()) {
    nodes[node.id as AnyNodeId] = node
  }
  return { nodes, rootNodeIds: ['site_rv'] as AnyNodeId[] }
}

export const template: SceneGraph = buildTemplate()

export const metadata = {
  id: 'rv-class-a',
  name: '40′ Class A motorhome',
  description:
    'RV envelope: chassis (pass-through bays), main living level, and roof reference plane, with a locked 40′ × 102″ exterior boundary and seven named basement bays.',
} as const
