import type { SceneGraph } from '@pascal-app/core/clone-scene-graph'
import type { AnyNode, AnyNodeId } from '@pascal-app/core/schema'

/**
 * 1991 Bluebird Wanderlodge WB40 (Wide Body, tag axle) envelope. Deterministic
 * ids (`site_rv`, `level_main`, …) are regenerated by `cloneSceneGraph` before
 * the template is applied.
 *
 * Coordinate frame: XZ plane, origin at coach center. Width (X) is the body
 * width; length (Z) runs front (−Z) to rear (+Z). Three levels stack in the
 * building: chassis (pass-through bays, level −1), main (living floor, level 0),
 * roof (reference plane for A/C, solar, vents, level 1).
 *
 * Dimensions are owner-measured for the specific coach: exterior body 102″ × 40′,
 * interior clear width 95″ (3.5″ sidewall build), interior ceiling 79″. The main
 * floor is split into a front 4′ cockpit and a 36′ cabin; the rear engine bay
 * sits below the cabin plane (chassis level), so the cabin runs full-length to
 * the rear wall. The planned raised hydronic-radiant floor is a gated remodel
 * overlay and is intentionally NOT part of this base envelope.
 */

const IN = 0.0254 // metres per inch
const FT = 0.3048 // metres per foot

const HALF_W = (102 * IN) / 2 // exterior body half-width (102")
const HALF_L = (40 * FT) / 2 // exterior body half-length (40')
const WALL_HEIGHT = 79 * IN // interior ceiling height (79")
const WALL_THICKNESS = 3.5 * IN // sidewall build (skin + frame + insulation + panel)

// Wall centrelines sit half a wall-thickness inboard of the body outline, so the
// outer face is the 102″×40′ body and the inner face gives the measured 95″
// interior clear width.
const WC_X = HALF_W - WALL_THICKNESS / 2
const WC_Z = HALF_L - WALL_THICKNESS / 2
// Interior clear extents (inner wall faces): half-width = 95″/2.
const IN_X = HALF_W - WALL_THICKNESS
const IN_Z = HALF_L - WALL_THICKNESS
const COCKPIT_LEN = 4 * FT // front cockpit depth; the remainder is the ~36′ cabin

// Bay boundaries along Z, front (−) to rear (+): 7 pass-through compartments.
// Lengths remain nominal pending owner bay measurements.
const BAY_BANDS: Array<{ role: string; name: string; z0: number; z1: number }> = [
  { role: 'generator', name: 'Generator bay', z0: -HALF_L, z1: -4.5 },
  { role: 'battery', name: 'Battery bay', z0: -4.5, z1: -3.3 },
  { role: 'propane', name: 'Propane bay', z0: -3.3, z1: -2.1 },
  { role: 'fresh-tank', name: 'Fresh water tank', z0: -2.1, z1: -0.5 },
  { role: 'grey-tank', name: 'Grey tank', z0: -0.5, z1: 1.0 },
  { role: 'black-tank', name: 'Black tank', z0: 1.0, z1: 2.5 },
  { role: 'engine', name: 'Engine bay', z0: 2.5, z1: HALF_L },
]

function buildNodes(): AnyNode[] {
  const site = {
    object: 'node',
    id: 'site_rv' as AnyNodeId,
    type: 'site',
    parentId: null,
    visible: true,
    metadata: {},
    polygon: {
      type: 'polygon',
      points: [
        [-8, -8],
        [8, -8],
        [8, 8],
        [-8, 8],
      ],
    },
    children: ['building_rv' as AnyNodeId],
  } as unknown as AnyNode

  const building = {
    object: 'node',
    id: 'building_rv' as AnyNodeId,
    type: 'building',
    parentId: 'site_rv' as AnyNodeId,
    visible: true,
    metadata: {},
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    children: ['level_chassis', 'level_main', 'level_roof'] as AnyNodeId[],
  } as unknown as AnyNode

  const wallDefs = [
    { id: 'wall_n', start: [-WC_X, -WC_Z], end: [WC_X, -WC_Z] },
    { id: 'wall_e', start: [WC_X, -WC_Z], end: [WC_X, WC_Z] },
    { id: 'wall_s', start: [WC_X, WC_Z], end: [-WC_X, WC_Z] },
    { id: 'wall_w', start: [-WC_X, WC_Z], end: [-WC_X, -WC_Z] },
  ]
  const walls = wallDefs.map(
    (w) =>
      ({
        object: 'node',
        id: w.id as AnyNodeId,
        type: 'wall',
        parentId: 'level_main' as AnyNodeId,
        visible: true,
        metadata: { locked: true },
        children: [],
        thickness: WALL_THICKNESS,
        height: WALL_HEIGHT,
        start: w.start,
        end: w.end,
        frontSide: 'unknown',
        backSide: 'unknown',
      }) as unknown as AnyNode,
  )

  // Interior floor split on the clear footprint: a front cockpit and the cabin.
  const cockpitZone = {
    object: 'node',
    id: 'zone_cockpit' as AnyNodeId,
    type: 'zone',
    parentId: 'level_main' as AnyNodeId,
    visible: true,
    metadata: { area: 'cockpit', locked: true },
    name: 'Cockpit',
    color: '#64748b',
    polygon: [
      [-IN_X, -IN_Z],
      [IN_X, -IN_Z],
      [IN_X, -IN_Z + COCKPIT_LEN],
      [-IN_X, -IN_Z + COCKPIT_LEN],
    ],
  } as unknown as AnyNode

  const cabinZone = {
    object: 'node',
    id: 'zone_cabin' as AnyNodeId,
    type: 'zone',
    parentId: 'level_main' as AnyNodeId,
    visible: true,
    metadata: { area: 'cabin' },
    name: 'Cabin',
    color: '#60a5fa',
    polygon: [
      [-IN_X, -IN_Z + COCKPIT_LEN],
      [IN_X, -IN_Z + COCKPIT_LEN],
      [IN_X, IN_Z],
      [-IN_X, IN_Z],
    ],
  } as unknown as AnyNode

  const bays = BAY_BANDS.map(
    (b) =>
      ({
        object: 'node',
        id: `zone_bay_${b.role}` as AnyNodeId,
        type: 'zone',
        parentId: 'level_chassis' as AnyNodeId,
        visible: true,
        metadata: { bayRole: b.role, locked: true },
        name: b.name,
        color: '#94a3b8',
        polygon: [
          [-HALF_W, b.z0],
          [HALF_W, b.z0],
          [HALF_W, b.z1],
          [-HALF_W, b.z1],
        ],
      }) as unknown as AnyNode,
  )

  const levelChassis = {
    object: 'node',
    id: 'level_chassis' as AnyNodeId,
    type: 'level',
    parentId: 'building_rv' as AnyNodeId,
    visible: true,
    metadata: {},
    level: -1,
    children: bays.map((b) => b.id) as AnyNodeId[],
  } as unknown as AnyNode

  const levelMain = {
    object: 'node',
    id: 'level_main' as AnyNodeId,
    type: 'level',
    parentId: 'building_rv' as AnyNodeId,
    visible: true,
    metadata: {},
    level: 0,
    children: [...walls.map((w) => w.id), 'zone_cockpit', 'zone_cabin'] as AnyNodeId[],
  } as unknown as AnyNode

  const levelRoof = {
    object: 'node',
    id: 'level_roof' as AnyNodeId,
    type: 'level',
    parentId: 'building_rv' as AnyNodeId,
    visible: true,
    metadata: {},
    level: 1,
    children: [],
  } as unknown as AnyNode

  return [site, building, levelChassis, levelMain, levelRoof, ...walls, cockpitZone, cabinZone, ...bays]
}

function buildTemplate(): SceneGraph {
  const nodes: Record<AnyNodeId, AnyNode> = {}
  for (const node of buildNodes()) {
    nodes[node.id as AnyNodeId] = node
  }
  return { nodes, rootNodeIds: ['site_rv'] as AnyNodeId[] }
}

export const template: SceneGraph = buildTemplate()

export const metadata = {
  id: 'rv-class-a',
  name: '40′ Class A motorhome',
  description:
    'RV envelope tuned to a 1991 Wanderlodge WB40: chassis (pass-through bays), main level split into cockpit + cabin, and roof reference plane, with a locked 102″×40′ body giving a 95″ interior clear width and a 79″ ceiling.',
} as const
